// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_FzREzxnaOFNYH5Pq0ZrVT0UIM64ptfk',
    appId: '1:146851567269:android:cd27487673b783f4aa5f4c',
    messagingSenderId: '146851567269',
    projectId: 'note-demo-cb0de',
    storageBucket: 'note-demo-cb0de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJMUTxBBwTQS8p-2Ok1XhIboPqbtzkshk',
    appId: '1:146851567269:ios:36c62e33ff7a4c3aaa5f4c',
    messagingSenderId: '146851567269',
    projectId: 'note-demo-cb0de',
    storageBucket: 'note-demo-cb0de.appspot.com',
    iosBundleId: 'co.timchi.flutternotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJMUTxBBwTQS8p-2Ok1XhIboPqbtzkshk',
    appId: '1:146851567269:ios:2eb299adfaeddbb6aa5f4c',
    messagingSenderId: '146851567269',
    projectId: 'note-demo-cb0de',
    storageBucket: 'note-demo-cb0de.appspot.com',
    iosBundleId: 'co.timchi.flutternotes.RunnerTests',
  );
}
